services:
  - type: web
    name: krushiyuga-website
    env: node
    plan: free
    region: oregon
    buildCommand: echo "CSS already built - skipping build step"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_USERNAME
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
      - key: MONGODB_CLUSTER
        sync: false
      - key: MONGODB_DATABASE
        value: krushiyuga
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_FIRSTNAME
        value: Abhishek
      - key: ADMIN_LASTNAME
        value: V
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
